import { app, BrowserWindow, screen } from "electron";
import appState from "./state";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let mainWindow: BrowserWindow;
let imageWindow: BrowserWindow;

export function createWindow(): void {
  const primaryDisplay = screen.getPrimaryDisplay();
  const { bounds } = primaryDisplay;

  const windowOptions: Electron.BrowserWindowConstructorOptions = {
    width: bounds.width,
    height: bounds.height,
    // x: bounds.x,
    // y: bounds.y,
    // frame: false,
    // fullscreen: false,
    // autoHideMenuBar: true,
    // transparent: true,
    // alwaysOnTop: true,
    // skipTaskbar: true,
    // movable: false,
    // resizable: false,
    // minimizable: false,
    // maximizable: false,
    // hasShadow: false,
    // enableLargerThanScreen: true,
    // focusable: false,
    show: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  };

  mainWindow = new BrowserWindow(windowOptions);

  mainWindow.removeMenu();

  mainWindow.webContents.session.webRequest.onHeadersReceived(
    (details, callback) => {
      callback({
        responseHeaders: {
          ...details.responseHeaders,
          "Content-Security-Policy": [
            "default-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https://firebasestorage.googleapis.com https://*.firebaseio.com https://*.googleapis.com; style-src 'self' 'unsafe-inline';",
          ],
        },
      });
    },
  );

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }

  mainWindow.on("close", (event) => {
    if (!appState.isQuitting) {
      event.preventDefault();
      mainWindow.hide();
    }
  });
}

export function getMainWindow(): BrowserWindow {
  return mainWindow;
}

export function showMainWindow(): BrowserWindow {
  const mainWindow = getMainWindow();
  if (mainWindow.isVisible()) {
    mainWindow.focus();
  } else {
    mainWindow.show();
  }
  return mainWindow;
}

export function hideMainWindow(): void {
  const mainWindow = getMainWindow();
  mainWindow.hide();
}

export function createImageWindow(dataURL: string) {
  const primaryDisplay = screen.getPrimaryDisplay();
  const { bounds } = primaryDisplay;

  const windowOptions: Electron.BrowserWindowConstructorOptions = {
    width: bounds.width,
    height: bounds.height,
    x: bounds.x,
    y: bounds.y,
    frame: false,
    fullscreen: false,
    autoHideMenuBar: true,
    transparent: true,
    alwaysOnTop: true,
    skipTaskbar: true,
    movable: false,
    resizable: false,
    minimizable: false,
    maximizable: false,
    hasShadow: false,
    enableLargerThanScreen: true,
    focusable: false,
    backgroundColor: "red",
    webPreferences: {
      contextIsolation: true,
    },
  };

  imageWindow = new BrowserWindow(windowOptions);

  imageWindow.setAlwaysOnTop(true, "screen-saver");
  imageWindow.loadURL(dataURL);
}

export function getImageWindow(): BrowserWindow {
  return imageWindow;
}

export function isImageWindowOpen(): boolean {
  return imageWindow && !imageWindow.isDestroyed();
}

export function closeImageWindow() {
  if (imageWindow && !imageWindow.isDestroyed()) {
    imageWindow.close();
  }
}
