name: Deploy to GAE
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - run: |
          echo "loading env file"
          echo "${{secrets.ENV_STG}}" | base64 --decode > .env.stg 
          pwd
          ls -al

      - uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
          service_account: '${{ secrets.APPENGINE_DEPLOY_SA_EMAIL }}'

      - id: 'deploy'
        name: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: 'app.yaml'
          project_id: '${{ secrets.GCP_PROJECT }}'

      - name: 'show output'
        run: 'echo ${{ steps.deploy.outputs.url }}'
